Skip to content
Search or jump toâ€¦
Pull requests
Issues
Marketplace
Explore
 
@ryusei-fujisaki 
budougumi0617
/
autorelease-by-release-it-on-actions
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
autorelease-by-release-it-on-actions/.github/workflows/release.yml
@budougumi0617
budougumi0617 ğŸ’š fix ci settings
Latest commit 26e88e4 on 26 Nov 2020
 History
 1 contributor
41 lines (41 sloc)  1.61 KB

name: auto release demo
on:
  push:
    # mainãƒ–ãƒ©ãƒ³ãƒã«ã‚³ãƒŸãƒƒãƒˆãŒpushã•ã‚ŒãŸã¨ãã«é™å®š
    branches:
      - main
    # ä¸Šè¨˜æ¡ä»¶ã«åŠ ãˆã¦genãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªé…ä¸‹ãŒå¤‰æ›´ã•ã‚ŒãŸã¨ãã®ã¿ã¨ã„ã†æ¡ä»¶ã‚’è¿½åŠ 
    paths:
      - gen/**
jobs:
  auto-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_IT_VERSION: 14.2.1
    steps:
      - name: Check out codes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Set releaser settings
        run: |
          git config --global user.name release-machine
          git config --global user.email email@example.com
      - name: Major release
        id: major
        if: contains(toJSON(github.event.commits.*.message), 'bump up version major')
        run:  npx release-it@${RELEASE_IT_VERSION} -- major --ci
      - name: Minor release
        id: minor
        # ãƒ¡ã‚¸ãƒ£ãƒ¼ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚¢ãƒƒãƒ—ã‚’ã—ã¦ã„ãªã„ã¨ããƒã‚¤ãƒŠãƒ¼ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚¢ãƒƒãƒ—ã‚’è¡Œãªã†ã‹
        if: steps.major.conclusion == 'skipped'  && contains(toJSON(github.event.commits.*.message), 'bump up version minor')
        run:  npx release-it@${RELEASE_IT_VERSION} -- minor --ci
      - name: Patch release
        # ã‚³ãƒŸãƒƒãƒˆãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã«ç‰¹ã«æŒ‡å®šãŒãªã„å ´åˆã¯ãƒã‚¤ãƒŠãƒ¼ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’æ›´æ–°ã™ã‚‹
        if: "!(steps.major.conclusion == 'success' || steps.minor.conclusion == 'success')"
        run:  npx release-it@${RELEASE_IT_VERSION} -- patch --ci